version: "3.9"

services:
  api:
    build: ./server
    container_name: portify-api
    restart: always
    environment:
      DATABASE_URL: "postgresql://portify:portify@portify-database-ydx9eu:5432/portify"
      JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
      PORT: 3000
    networks:
      - dokploy-network

  ui:
    build: ./portify-ui
    container_name: portify-ui
    restart: always
    depends_on:
      - api
    networks:
      - dokploy-network

volumes:
  postgres_data:

networks:
  dokploy-network:
    external: true
